version: 2
updates:

  # Maintain dependencies for client code
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "ui npm"
      include: "scope"
    open-pull-requests-limit: 3

  # Maintain dependencies for services code
  - package-ecosystem: "npm"
    directory: "/lambda/sheets"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "fn npm"
      include: "scope"
    open-pull-requests-limit: 3
