on: workflow_call
permissions: {}

jobs:
  build-app:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #actions/setup-node@v7
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: mkdir -p ./nmemonica-voice-en/pkg

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 #actions/download-artifact@v8
        with:
          name: nmemonica-voice-en
          path: nmemonica-voice-en/pkg

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #actions/checkout@v7
        with:
          path: nmemonica

      - run: |
          cd ./nmemonica
          npm ci

      - run: |
          cd ./nmemonica
          npm run build

      - name: Build Summary
        if: vars.CI_DEBUG == 'true'
        run: |
          touch build_summary.md
          echo "# Build Summary" >> build_summary.md
          echo "#### nmemonica" >> build_summary.md
          echo "<pre>" >> build_summary.md
          ls -hal ./nmemonica/dist >> build_summary.md
          echo "</pre>" >> build_summary.md
          echo "#### version" >> build_summary.md
          echo "<pre>" >> build_summary.md
          cat ./nmemonica/dist/component_versions.json >> build_summary.md
          echo "</pre>" >> build_summary.md
          cat build_summary.md >> $GITHUB_STEP_SUMMARY

      - name: App Version
        if: vars.CI_DEBUG != 'true'
        run: |
          touch build_summary.md
          echo "# Build Summary" >> build_summary.md
          echo "#### version" >> build_summary.md
          echo "<pre>" >> build_summary.md
          cat ./nmemonica/dist/component_versions.json >> build_summary.md
          echo "</pre>" >> build_summary.md
          cat build_summary.md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #actions/upload-artifact@v7
        with:
          name: dist
          path: nmemonica/dist/
          compression-level: 0
          retention-days: 1
