name: DCO Checks
on: push

jobs:
  check-dco-signoff:
    environment: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Check DCO Signoff
        run: |
          head_sha=${{ github.sha }}
          init_sha=${head_sha:0:8}
          main_sha=$(gh api repos/${{ github.repository }}/commits/main | jq -r '.sha')
          commits_details=$(gh api repos/${{ github.repository }}/compare/${main_sha}...${head_sha} | jq -r ".commits[] | { sha: .sha, name: .commit.author.name, email: .commit.author.email, date: .commit.author.date, message: .commit.message}")
          readarray -t pr_commits < <(echo $commits_details | jq -c ".")
          touch summary.md
          echo "# $GITHUB_REF_NAME Commits ${#pr_commits[@]}" >> summary.md
          echo "##### Commit Details" >> summary.md
          echo "<pre>" >> summary.md
          for commit in "${pr_commits[@]}"; do echo $commit | jq -r '"commit \(.sha)\nAuthor: \(.name) <\(.email)>\nDate: \(.date)\n\(.message)\n"' >> summary.md; done
          echo "</pre>" >> summary.md
          echo -e "\n---\n" >> summary.md;
          echo "##### DCO Summary" >> summary.md
          echo "<pre>" >> summary.md
          for commit in "${pr_commits[@]}"; do commit_sha=$(echo $commit | jq -r ".sha"); echo $commit | jq -r ".message" | grep "Signed-off-by:" | xargs echo "${commit_sha:0:8} - " >> summary.md; done
          echo -e "</pre>" >> summary.md
          cat summary.md >> $GITHUB_STEP_SUMMARY
          set -e
          for commit in "${pr_commits[@]}"; do echo $commit | jq -r ".message" | grep "Signed-off-by:"; done
        env:
          GH_TOKEN: ${{ github.token }}