on: push
permissions: {}

env:
# from: konsumer/install-wasi-sdk@v1
  CC: '/opt/wasi-sdk/bin/clang'
  AR: '/opt/wasi-sdk/bin/llvm-ar'

jobs:
  build-w-private-deps:
    environment: ci
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #actions/setup-node@v7
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 #actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.NMEMONICA_BUILD_CLIENT_ID }}
          private-key: ${{ secrets.NMEMONICA_BUILD_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #actions/checkout@v7
        with:
          path: nmemonica

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #actions/checkout@v7
        with:
          repository: bryanjimenez/nmemonica-voice-en
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          submodules: 'recursive'
          ref: 'third-party-notice'
          path: nmemonica-voice-en

      - name: install-wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f #actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      # dedicated action cargo-license https://github.com/onur/cargo-license/issues/45
      - uses: actions-rs/install@9da1d2adcfe5e7c16992e8242ca33a56b6d9b101 #actions-rs/installv0.1
        with:
          crate: cargo-license
          version: latest

      # FIXME: remplace konsumer/install-wasi-sdk w/ bytecodealliance/setup-wasi-sdk-action
      # - name: install-wasi-sdk
      #   uses: bytecodealliance/setup-wasi-sdk-action@77d09f3df1e8da344d8403cf8631af8977938b4c #bytecodealliance/setup-wasi-sdk-action@v1
      #   with:
      #     version: '25'

      # https://github.com/WebAssembly/wasi-sdk/issues/468
      - name: install-wasi-sdk
        uses: konsumer/install-wasi-sdk@d728b7abb7ef7db1610039d9798a8270e23f56f8 #konsumer/install-wasi-sdk@v1
        with:
          version: '25'
          add-to-path: 'false'

      - name: build-release
        run: |
          cd ./nmemonica-voice-en
          cargo build --release --target wasm32-unknown-unknown

      - name: build-wasm
        run: |
          cd ./nmemonica-voice-en
          wasm-pack build ./voice-en --out-dir ../pkg --scope nmemonica --release

      # FIXME: mock ThirdPartyLicense.json need cargo-license
      # echo "[]" > ./pkg/ThirdPartyLicense.json
      - name: tgz-wasm
        run: |
          cd ./nmemonica-voice-en
          node ./pkg_helper.js third-party
          wasm-pack pack

      - run: |
          cd ./nmemonica
          npm ci

      - run: |
          cd ./nmemonica
          npm run build

      - run: |
          touch build_summary.md
          echo "# Build Summary" >> build_summary.md
          echo "#### nmemonica" >> build_summary.md
          echo "<pre>" >> build_summary.md
          ls -la ./nmemonica/build >> build_summary
          echo -e "</pre>" >> build_summary.md
          echo "#### nmemonica-voice-en" >> build_summary.md
          echo "<pre>" >> build_summary.md
          ls -la ./nmemonica-voice-en/pkg >> build_summary
          echo -e "</pre>" >> build_summary.md
          cat build_summary.md >> $GITHUB_STEP_SUMMARY
      # - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #actions/upload-artifact@v7
      #   with: 
      #     name: dist
      #     path: dist/
